name: Github Readme Creater Workflow

on: workflow_dispatch # [workflow_dispatch, repository_dispatch, schedule, workflow_call]

jobs: 
  first-job: 
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello
        run: echo "hello"
      - name: Print ByeBye
        run: echo "bye bye"



