name: Github Readme Creater Workflow

on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 0 * * *' # daily at 00:00 UTC

permissions:
  contents: write

jobs: 
  first-job: 
    runs-on: ubuntu-latest
    concurrency:
      group: profile-readme-daily
      cancel-in-progress: false
    steps:
      - name: Get Code 
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          persist-credentials: true
      - name: "Set up Python"
        uses: actions/setup-python@v6
        with:
          python-version-file: ".python-version"
      - name: Install uv
        uses: astral-sh/setup-uv@v6
      - name: Install the project
        run: uv sync --locked --all-extras --dev
      - name: Cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/cache/requirements.txt') }}
          restore-keys: ${{ runner.os }}-pip-
      - name: Add env file
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          USER_NAME: ${{ secrets.USER_NAME }}
        run: uv run main.py
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: Serhat Karaman
          author_email: serhatkaramanworkmail@gmail.com
          message: 'Updated profile Readme'
          add: '.'
          token: ${{ secrets.ACCESS_TOKEN }}